### ISSUE TITLE
добавить dom-utils в зависимости

### ISSUE THREAD

**Issue by balesniy** [htmlacademy/linthtml-rules-htmlacademy#11]
```
"devDependencies": {
    "@linthtml/dom-utils": "^0.9.5"
  }
```

**Comment by nikolai-shabalin** [comment]
Так вроде же есть
![image](https://github.com/htmlacademy/linthtml-rules-htmlacademy/assets/2378233/ae510931-c8f1-47c5-bdd2-5ed2411b9fae)
приходят вместе с `@linthtml/linthtml`

**Comment by balesniy** [comment]
да, но в нашем пакете линтера нет) а правила мы на его утилиты завязываем.

**Comment by nikolai-shabalin** [comment]
Да, для `devDependencies` согласен
