### ISSUE TITLE
Правило: attr-spacing

### ISSUE THREAD

**Issue by balesniy** [htmlacademy/linthtml-rules-htmlacademy#50]
### Краткое описание

 attributes must be separated by whitespace

### Плохие примеры

`<input type="submit"class="foo">`

### Хорошие примеры

`<input type="submit" class="foo">`

**Comment by nikolai-shabalin** [comment]
Проверить в валидаторе

**Comment by nikolai-shabalin** [comment]
валидатор ругается значит проверять в линтере не будем
