### ISSUE TITLE
Правило: script-?

### ISSUE THREAD

**Issue by balesniy** [htmlacademy/linthtml-rules-htmlacademy#52]
### Краткое описание

Скрипты подключены в самом низу страницы, чтобы при её загрузке не блокировать отображение содержимого.

### Плохие примеры

```
<html lang="ru">
  <head>
    <script src="app.js"></script>
  </head>
  <body>…</body>
</html>
```

### Хорошие примеры

```
<html lang="ru">
  <head>…</head>
  <body>
    <!-- Содержимое страницы -->
    <script src="app.js"></script>
  </body>
</html>
```

**Comment by nikolai-shabalin** [comment]
`script-position`

**Comment by what1s1ove** [comment]
@nikolai-shabalin подскажите, данное правило, как и сам плагин, больше заточен на Академию?

Вопрос в следующем, некоторые интеграции/библиотеки требуют инлайновые теги скриптов[^1] в специфичном месте в документе (обычно рядом там, где происходит само встраивание необходимых элементов для библиотеки), и так как данное правило триггериться на любой скрипт который не `defer`, `async` или не в конце документа, получаю ошибку. 

Так как я не могу влиять на то, где нужно будет вставить инлайновый скрипт библиотеки, а при добавлении `defer` или `async` на инлайновый скрипт, что не совсем валидно и w3c валидатор начинает ругаться, предлагаю добавить исключение к данному правилу, чтобы оно не ругалось на инлайновые скрипты.

<img width="1712" alt="image" src="https://github.com/htmlacademy/linthtml-rules-htmlacademy/assets/42296182/a0df1a51-196d-4bae-9b2c-8346af5aa724">

<img width="1726" alt="image" src="https://github.com/htmlacademy/linthtml-rules-htmlacademy/assets/42296182/7429ab80-c687-4642-a19b-7f6385741b47">

Но это, как по мне, задача, которая выходит за рамки академии. Поэтому не знаю на сколько оно будет для вас валидно 😁

[^1]: Те скрипты, которые подключают не внешний файл скрипта через `src` атрибут, а где сам скрипт пишется непосредственно в самом теге `script`
