### ISSUE TITLE
Проблема: htmlacademy/attr-req-value вместе с select

### ISSUE THREAD

**Issue by what1s1ove** [htmlacademy/linthtml-rules-htmlacademy#82]
### Ошибка из терминала

```
 23:15  error  The attribute "value" requires a value  htmlacademy/attr-req-value 
 29:15  error  The attribute "value" requires a value  htmlacademy/attr-req-value
```

### Часть кода на котором произошла ошибка

```
<label for="fruits">Fruits</label>
<select name="fruits" required>
  <option value="">Select...</option>
  <option value="banana">Banana</option>
  <option value="apple">Apple</option>
</select>
```

### Описание проблемы

Селект с `value=""` в опшине разрешен спекой.

Юзкейс: когда нужно сделать селект обязательным для заполнения, но по умолчанию не нужно давать никакого значения (для этого и используется опишн с пустым значением).

**Comment by nikolai-shabalin** [comment]
Спасибо. Уже в работе

**Comment by nikolai-shabalin** [comment]
@what1s1ove , привет.

Есть пара вопросов. Подскажи пожалуйста.

1. Пример, когда `value` пустой для двух `<option>` в одном `<select>` является ошибочным? Я сейчас написал проверку, что `<option value="">` с пустым значением может быть только в единственном экземляре в `<select>`.
```html
<select name="fruits" required>
  <option value="">Select...</option>
  <option value="">Banana</option>
  <option value="apple">Apple</option>
</select>
```

2. Для твоего примера у `<option>` не должно быть атрибутов `selected disabled` или у пользователя должна быть возможность вернуться к пустому "Select.."?

**Comment by what1s1ove** [comment]
> @what1s1ove , привет.
> 
> Есть пара вопросов. Подскажи пожалуйста.
> 
> 1. Пример, когда `value` пустой для двух `<option>` в одном `<select>` является ошибочным? Я сейчас написал проверку, что `<option value="">` с пустым значением может быть только в единственном экземляре в `<select>`.
> 
> ```
> <select name="fruits" required>
>   <option value="">Select...</option>
>   <option value="">Banana</option>
>   <option value="apple">Apple</option>
> </select>
> ```
> 
> 2. Для твоего примера у `<option>` не должно быть атрибутов `selected disabled` или у пользователя должна быть возможность вернуться к пустому "Select.."?

Привет @nikolai-shabalin !

1. Я думаю да, хоть в спеке ничего не нашел про это. В голову точно не приходит ни одного кейса, где нужно было бы иметь больше чем один `option` с пустым `value`... . Спасибо что добавил проверку! Мне кажется она очень полезная.
2. В практике не было такого чтобы я вешал `disabled`. `selected` в целом может быть, но так как этот `option` _обычно_ идет первым, он будет выбран по умолчанию. Вообщем в моей практике добавления данных атрибутов на "дефолтный" `option` не было. Как мне кажется, это какие-то эдж-кейсы, которые обрабатываются уже JS`ом, когда пользователь непосредственно уже взаимодействует со страницей. Линтер про них знать не будет, так как обычно линтер проверяет код который отправляется пользователю, но то что будет с ним дальше, и как JS будет изменять атрибуты, он не в курсе.

**Comment by nikolai-shabalin** [comment]
1. Спекой пускай валидатор занимается. Задача этого пакета улучшать качество HTML-разметки, не нарушая валидацию. Мы можем придумать дополнительные правила по написанию разметки =)
2. Спасибо, тогда не буду учитывать наличие этих атрибутов

**Comment by nikolai-shabalin** [comment]
Можно обновить пакет до версии `1.0.16`. 

`npm i linthtml-rules-htmlacademy@1.0.16`

**Comment by what1s1ove** [comment]
> Можно обновить пакет до версии `1.0.16`.
> 
> `npm i linthtml-rules-htmlacademy@1.0.16`
> 
> Спасибо за предложение

Спасибо за реализацию!
